spring.application.name=FileSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/ArchivingFileSystem_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
#15min
jwt.access-expiration=900000
#7 days
jwt.refresh-expiration=604800000
#30 days
jwt.remember-me-expiration=2592000000
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariConnPool

logging.level.com.zaxxer.hikari=TRACE
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

#to identify connection leak ?
spring.datasource.hikari.leak-detection-threshold=2000


file-storage.upload-dir=${FILE_STORAGE_UPLOAD_DIR:./uploads}
file-storage.trash-dir=${FILE_STORAGE_TRASH_DIR:./trash}


