spring.application.name=FileSystem


spring.datasource.url=jdbc:postgresql://localhost:5432/ArchivingFileSystem_db
spring.datasource.username=postgres
spring.datasource.password=sqlpost123@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=4KyRiX1-86-tjRps_4VxU5OPy_LS_V1tAXI7bYMmxudr-Vo9eX3bHBCsHVIhhQ5z
jwt.access-expiration=900000
jwt.refresh-expiration=604800000