package com.ADIB.FileSystem.Enum;

public enum PERMISSION_NAME {
    DEPARTMENT_READ,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_DELETE,

    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,

    FILE_UPLOAD,
    FILE_DOWNLOAD,
    FILE_DELETE,
    FILESTATUS_UPDATE,

    FILETYPE_READ,
    FILETYPE_CREATE,
    FILETYPE_UPDATE,
}
